export const listeningExams = [
  {
    id: 1,
    exam_name: "Listening Test 1",
    exam_type: "Listening",
    category: "ielts",
    subCategory: "listening",
  },
  {
    id: 2,
    exam_name: "Listening Test 2",
    exam_type: "Listening",
    category: "ielts",
    subCategory: "listening",
  },
  {
    id: 3,
    exam_name: "Listening Test 3",
    exam_type: "Listening",
    category: "ielts",
    subCategory: "listening",
  },
  {
    id: 4,
    exam_name: "Listening Test 4",
    exam_type: "Listening",
    category: "ielts",
    subCategory: "listening",
  },
  {
    id: 5,
    exam_name: "Listening Test 5",
    exam_type: "Listening",
    category: "ielts",
    subCategory: "listening",
  },
  {
    id: 6,
    exam_name: "Listening Test 6",
    exam_type: "Listening",
    category: "ielts",
    subCategory: "listening",
  },
  {
    id: 7,
    exam_name: "Listening Test 7",
    exam_type: "Listening",
    category: "ielts",
    subCategory: "listening",
  },
  {
    id: 8,
    exam_name: "Listening Test 8",
    exam_type: "Listening",
    category: "ielts",
    subCategory: "listening",
  },
  {
    id: 9,
    exam_name: "Listening Test 9",
    exam_type: "Listening",
    category: "ielts",
    subCategory: "listening",
  },
  {
    id: 10,
    exam_name: "Listening Test 10",
    exam_type: "Listening",
    category: "ielts",
    subCategory: "listening",
  },
];
