[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/oeccrm/*"
  to = "/crm/:splat"
  status = 200

[[redirects]]
  from = "/crm/login"
  to = "/crm/index.html"
  status = 200

[[redirects]]
  from = "/crm/*"
  to = "/crm/index.html"
  status = 200

[[redirects]]
  from = "/courses"
  to = "/popular-courses"
  status = 301

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/crm/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; font-src 'self' data:; connect-src 'self' https: wss: ws:; frame-ancestors 'self';"

[[headers]]
  for = "/oeccrm/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; font-src 'self' data:; connect-src 'self' https: wss: ws:; frame-ancestors 'self';"