[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/oeccrm/*"
  to = "/crm/:splat"
  status = 200

[[redirects]]
  from = "/crm/login"
  to = "/crm/index.html"
  status = 200

[[redirects]]
  from = "/crm/*"
  to = "/crm/index.html"
  status = 200

[[redirects]]
  from = "/courses"
  to = "/popular-courses"
  status = 301

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/crm/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob: https: http:; script-src 'self' 'unsafe-eval' 'unsafe-inline' https: http: data: blob:; style-src 'self' 'unsafe-inline' https: http: data:; img-src 'self' data: blob: https: http:; font-src 'self' data: https: http:; connect-src 'self' https: http: wss: ws: data:; media-src 'self' data: blob: https: http:; object-src 'none'; base-uri 'self'; frame-ancestors 'self'; worker-src 'self' blob:; child-src 'self' blob:;"

[[headers]]
  for = "/oeccrm"
  [headers.values]
    Content-Security-Policy = "script-src * 'unsafe-eval' 'unsafe-inline' data: blob:; default-src * 'unsafe-inline' 'unsafe-eval' data: blob:; style-src * 'unsafe-inline' data:; img-src * data: blob:; font-src * data:; connect-src * data:; media-src * data: blob:; object-src *; base-uri *; frame-ancestors *; worker-src * blob:; child-src * blob:;"

[[headers]]
  for = "/oeccrm/*"
  [headers.values]
    Content-Security-Policy = "script-src * 'unsafe-eval' 'unsafe-inline' data: blob:; default-src * 'unsafe-inline' 'unsafe-eval' data: blob:; style-src * 'unsafe-inline' data:; img-src * data: blob:; font-src * data:; connect-src * data:; media-src * data: blob:; object-src *; base-uri *; frame-ancestors *; worker-src * blob:; child-src * blob:;"