export const writingExams = [
  {
    id: 1,
    exam_name: "Writing Test 1",
    exam_type: "Writing",
    category: "ielts",
    subCategory: "writing",
  },
  {
    id: 2,
    exam_name: "Writing Test 2",
    exam_type: "Writing",
    category: "ielts",
    subCategory: "writing",
  },
  {
    id: 3,
    exam_name: "Writing Test 3",
    exam_type: "Writing",
    category: "ielts",
    subCategory: "writing",
  },
  {
    id: 4,
    exam_name: "Writing Test 4",
    exam_type: "Writing",
    category: "ielts",
    subCategory: "writing",
  },
  {
    id: 5,
    exam_name: "Writing Test 5",
    exam_type: "Writing",
    category: "ielts",
    subCategory: "writing",
  },
  {
    id: 6,
    exam_name: "Writing Test 6",
    exam_type: "Writing",
    category: "ielts",
    subCategory: "writing",
  },
  {
    id: 7,
    exam_name: "Writing Test 7",
    exam_type: "Writing",
    category: "ielts",
    subCategory: "writing",
  },
  {
    id: 8,
    exam_name: "Writing Test 8",
    exam_type: "Writing",
    category: "ielts",
    subCategory: "writing",
  },
  {
    id: 9,
    exam_name: "Writing Test 9",
    exam_type: "Writing",
    category: "ielts",
    subCategory: "writing",
  },
  {
    id: 10,
    exam_name: "Writing Test 10",
    exam_type: "Writing",
    category: "ielts",
    subCategory: "writing",
  },
];
