export const readingExams = [
  {
    id: 1,
    exam_name: "Reading Test 1",
    exam_type: "Reading",
    category: "ielts",
    subCategory: "reading",
  },
  {
    id: 2,
    exam_name: "Reading Test 2",
    exam_type: "Reading",
    category: "ielts",
    subCategory: "reading",
  },
  {
    id: 3,
    exam_name: "Reading Test 3",
    exam_type: "Reading",
    category: "ielts",
    subCategory: "reading",
  },
  {
    id: 4,
    exam_name: "Reading Test 4",
    exam_type: "Reading",
    category: "ielts",
    subCategory: "reading",
  },
  {
    id: 5,
    exam_name: "Reading Test 5",
    exam_type: "Reading",
    category: "ielts",
    subCategory: "reading",
  },
  {
    id: 6,
    exam_name: "Reading Test 6",
    exam_type: "Reading",
    category: "ielts",
    subCategory: "reading",
  },
  {
    id: 7,
    exam_name: "Reading Test 7",
    exam_type: "Reading",
    category: "ielts",
    subCategory: "reading",
  },
  {
    id: 8,
    exam_name: "Reading Test 8",
    exam_type: "Reading",
    category: "ielts",
    subCategory: "reading",
  },
  {
    id: 9,
    exam_name: "Reading Test 9",
    exam_type: "Reading",
    category: "ielts",
    subCategory: "reading",
  },
  {
    id: 10,
    exam_name: "Reading Test 10",
    exam_type: "Reading",
    category: "ielts",
    subCategory: "reading",
  },
];
